### ISSUE TITLE
How to update the proposed Community Standard

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#10]
There is a full copy of the specification in this GitHub repository. When should we insist on PRs from branches and forks, and when should we do updates in-place on the master branch?

**Comment by chris-little** [comment]
I propose that full PRs are done for significant edits, then we have slightly formal, but still ad hoc, meetings to record the group decisions on each PR. 
We shold only do trivial edits in place, such as typos, formatting and grammar, but we should not have a succession of lots of little/small edits, as it makes life fiddly for those following the repo.
Thoughts?

**Comment by jonblower** [comment]
I think typos/grammatical edits that don't change the meaning or structure could be done in-place

**Comment by chris-little** [comment]
Agreed 2021-11-10 PRs for substantive changes, and a few inpalce edits for typos (to be kept to a minimum, to avoid too many notifications.
At least 2 reviewers for PRs.
