### ISSUE TITLE
How should we process the 22 outstanding CoverageJSON issues

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#11]
The [original specification](https://covjson.org/) has about 20 [issues outstanding](https://github.com/covjson/specification/issues). We need to discuss which can be addressed and incorporated into the proposed OGC Community Standard (assuming strong backward compatibility) and which are future work or enhancements.

Should we copy them across to here, or leave them in the original repo?

**Comment by chris-little** [comment]
@lewismc As we are:
1. Making good progress with addressing the Vote comments; 
2. Producing a schema for conformance testing;
3. Setting up project framework in the repo;
could you transfer across the 20 outstanding issues from the original COvJSON repo please?

**Comment by jonblower** [comment]
@chris-little @lewismc could we chat about this before transferring the issues please? There may be some that could be closed, or left where they are. I'm just trying to figure out how to best organise things between the original and OGC repos in general. (Sorry I missed the call yesterday.)

**Comment by chris-little** [comment]
@jonblower @lewismc  Does this list of Issue titles help? We could edit while we discuss, then bring across the agreed list.

https://github.com/covjson/specification/issues/95 needs discussion
https://github.com/covjson/specification/issues/94 needs discussion
https://github.com/covjson/specification/issues/93 needs discussion
https://github.com/covjson/specification/issues/91
https://github.com/covjson/specification/issues/88 crs 5 tasks
https://github.com/covjson/specification/issues/86 needs discussion
https://github.com/covjson/specification/issues/82
https://github.com/covjson/specification/issues/81 needs discussion
https://github.com/covjson/specification/issues/78
https://github.com/covjson/specification/issues/75 needs discussion
https://github.com/covjson/specification/issues/71 needs discussion
https://github.com/covjson/specification/issues/66 needs discussion 1.0
https://github.com/covjson/specification/issues/63 needs discussion
https://github.com/covjson/specification/issues/61 needs discussion
https://github.com/covjson/specification/issues/60
https://github.com/covjson/specification/issues/55 needs discussion 1.0
https://github.com/covjson/specification/issues/45 needs discussion 1.0
https://github.com/covjson/specification/issues/38 needs discussion future
https://github.com/covjson/specification/issues/32 needs discussion future
https://github.com/covjson/specification/issues/29 needs discussion future
https://github.com/covjson/specification/issues/15 needs discussion 1.0
https://github.com/covjson/specification/issues/3 needs discussion future

**Comment by lewismc** [comment]
OK to state the obvious it looks like there is a lot of discussion needed. Can the ones _without_ a qualifying comment can be moved over?

**Comment by letmaik** [comment]
I commented on and closed 13 of those issues for various reasons: out of scope, not an issue, etc.

The remaining ones are:

Ideally looked at before first release:

- Potentially backwards-incompatible: https://github.com/covjson/specification/issues/88
- Potentially backwards-incompatible: https://github.com/covjson/specification/issues/94

Can be deferred to a future version:

- Comparison: https://github.com/covjson/specification/issues/60
- Comparison: https://github.com/covjson/specification/issues/86
- Backwards-compatible: https://github.com/covjson/specification/issues/95
- Backwards-compatible: https://github.com/covjson/specification/issues/93
- Backwards-compatible: https://github.com/covjson/specification/issues/81
- Backwards-compatible: https://github.com/covjson/specification/issues/45

**Comment by jonblower** [comment]
Thanks for doing this @letmaik!

How about we move the "comparison" discussions to this (OGC) repo, as they are not so much about CovJSON itself, but more about its place in the world?

From my point of view, I'd like to discuss 88, 93 and 94 a bit further, as we've had specific user requests about these topics. It would be good to establish whether we need them for a first release.

I agree that the other tickets can wait until a future version. The "multiple time axes" one (number 45) is something that @chris-little has flagged before, so he might want to consider making this in scope for the first release too. But my feeling is that there won't be many people wanting to create CovJSON objects that have two time axes (although they may very well want to interrogate a back-end dataset that has them). I wonder how this would interact with the behaviour of an API like EDR?

**Comment by chris-little** [comment]
@jonblower I am happy for multiple time axes to be deferred to a later version.
As for the API-EDR, there is a presumption that there are 4 coordinates for any data (x,y,z,t), but we are addng to the maintenance release next week to possiblity of further 'coordinate' axes, consistently with the other OGC APIs.

**Comment by chris-little** [comment]
@letmaik @lewismc @jonblower @jerstlouis After Maik's helpful comments, I will create new issues in this repo for the outstanding topics.

**Comment by chris-little** [comment]
@jonblower I have `copied` , so people can pursue issues in either place, unless we decide otherwise. Let us discuss and close issues and leave their counterparts open, as we agree.
I am keen that the CoverageJSON repo does have a full recognition of the issues with the format, even if discussions take place elsewhere.

**Comment by chris-little** [comment]
2022-03-23 agreed to close as all relevant issues now have a current entry in this repo.
