### ISSUE TITLE
Various editorial improvements: IPR, source and validity

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#112]
@cnreed has made, and will make, several useful improvements to the phrasing and grammar of the specification.

**Comment by chris-little** [comment]
@cnreed We will make a PR including your suggestions. Do you wish to be a reviewer of the changes?

**Comment by cnreed** [comment]
Hi @chris-little, thank you for trying to include me in your project, unfortunately, I think you have the wrong person. Best of luck with your project! 😃

**Comment by chris-little** [comment]
Carl Reed suggested two additional clauses that the OAB determined needed to be added to the introductory clauses: 
Source of the document; and Validity of the document. You do have some of this in the Scope but they are supposed to be separate clauses.

ii. Source of this document
The majority of the content in this OGC document is a direct copy of the content originally contained at [https://covjson.org/spec/](https://covjson.org/spec/) . No normative changes have been made to the content. This OGC document does contain content not in source CovJSON GitHub repository. Specifically, while derived from content on the original [CovJSON repository](https://covjson.org/spec/), the Abstract, Keywords, Preface, Submitting Organizations, Endorsers, Terms and Definitions, and References sections and Annex B (Bibliography) in this document are not found on the [CovJSON](https://covjson.org/spec/). The Terms and Definitions and References sections may be added into the CovJSONi community GitHub repository in the future.
iii. Validity of content
The Submission Team has reviewed and certified that the snapshot content in this Community Standard is true and accurate. The snapshot for OGC CoverageJSON Version 1.0 was taken on April 23, 2022 from the CovJSON Version 0.2 GitHub Repository.

Also, it is interesting that the standard OGC License agreement is used. Typically, this standard agreement is for full blown OGC standards and not community standards. This is because to use the OGC license, the submission team (and probably the community) need to agree to transfer all intellectual property (IPR) to the OGC, totally unencumbered.

 This is why, for example, other Community Standards have various licensing and rights to use agreements. For example, again, check out I3S.

**Comment by letmaik** [comment]
https://covjson.org/spec/ is not appropriate anymore since it links to the OGC draft only. I suggest https://github.com/covjson/specification.

**Comment by chris-little** [comment]
@letmaik Thanks for this - @jonblower  and I were discussing exactly that this afternoon, but were side-tracked by other meetings. I have continued enitting the above comment and the two new clauses (ii and iii) should now be close to a final version.

There are IPR statements taht refer to University of Reading, but the OGC paragraphs were probably brought in automatically from the template.

**Comment by chris-little** [comment]
@cnreediii, @ghobona I created PR #120  to incorpoate missing sections and preferred security statement.

**Comment by chris-little** [comment]
@cnreddiii, @ghobona PR #120 has been reviewed and merged, so now closing this issue.
