### ISSUE TITLE
Conformance tests

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#12]
Are there any existing conformance tests? Do we need to create any? and documennt them in an Annex A?

**Comment by chris-little** [comment]
@lewismc As @ogcscotts said in his email, if there is a SHALL/MUST statement in the spec, there should be a test to confirm. It could be just a manual inspection of data or software or output. So we need to number the SHALL/MUST requirements in the spec.

**Comment by lewismc** [comment]
From Carl Reed
> An Abstract Test Suite (usually Annex A in an OGC standard) is an optional
clause in an OGC Community Standard (CS). Conformance tests are then
developed based on the guidance provided in the ATS. The ATS itself is
based on requirements and requirements classes as defined in the normative
content of the community standard. As a CS does not have to specify
requirements in the same manner as a standard developed and documented in
the OGC, developing an ATS may be a bit more interesting. Basically, any
"shall" or "must" is a requirement and an ATS and related conformance tests
developed could be defined based on those statements.

**Comment by lewismc** [comment]
Comments from Scott and Carl both agree as you state @chris-little

**Comment by jonblower** [comment]
I would love to have a tool (like the [cf-checker](https://github.com/cedadev/cf-checker)) that checks the validity and internal consistency of a CovJSON document. IMHO this is more practically useful than a written ATS for a normal user, although maybe we need both (one can inform the other of course). We started to develop a tool based on json-schema, but it turned out to be harder than we thought and ran out of time!

**Comment by jonblower** [comment]
I took another look at JSON Schema, which has moved on since I last looked (previously it wasn't sufficiently expressive to capture certain things). I wonder whether a good-quality schema would suffice as conformance tests? A schema can cover a lot of ground in a compact (and executable) form, rather than English text which might be longer and simply end up repeating the spec.

**Comment by lewismc** [comment]
I generally agree @jonblower

**Comment by ghobona** [comment]
@jonblower An Executable Test Suite (ETS) is implemented to run the tests that are specified in an Abstract Test Suite (ATS). Whereas an ATS is human-readable, an ETS is typically implemented in some programming language.

If you implement an ETS for CoverageJSON in Java, then it can be easily integrated into the OGC Validator for use by the ETS of OGC API - EDR, for instance. 

NOTE: For the EDR API, we are planning to use this library to support validation through JSON Schema https://github.com/everit-org/json-schema#quickstart

**Comment by jonblower** [comment]
Thanks @ghobona, that's very helpful. I'm still struggling a bit to imagine what an ATS might look like for a data format. Would it not simply be restating the specification? It seems that it could be a bit redundant.

**Comment by ghobona** [comment]
@jonblower The abstract tests found in the ATS assess whether an implementation of the standard meets the requirements stated in the Standard.

So how you write a particular abstract test depends on what requirement(s) you are testing for compliance to.

For an example, please have a look at EO-GeoJSON https://docs.ogc.org/is/17-003r2/17-003r2.html#60

**Comment by jonblower** [comment]
Thanks @ghobona! The EO-GeoJSON ATS basically says "try validating against the schema" for each of the classes involved. I was imagining that the ATS would be at a lower level (e.g. "verify that if property x is present, then property y has the value 'foo'"), which would just repeat the equivalent requirement in the spec.

So for CovJSON, if we create schema, our ATS could presumably follow this simple and practical approach.

**Comment by ghobona** [comment]
@jonblower Yes, the approach taken by EO-GeoJSON is preferable.

**Comment by chris-little** [comment]
Good progress is being made with the development of a JSON Schema for  CoverageJSON. Validation tools are also being developed.
Compatible and consistent schema fragments are being added to the API-EDR V1.0.1, but will be removed when CoverageJSON becomes a standard.

**Comment by jonblower** [comment]
Just an update on the JSON schema - this is getting close to completion. At present there are tests for the whole "core" spec and 7 out of 12 of the domain types. (There are currently a total of 2700 tests, many of which are auto-generated!) Hoping to round this off soon.

I also note that we might want a companion Python script to check rules that are not easily checked by JSON scheme.

**Comment by chris-little** [comment]
The schema has been finished as a V1.0 release candidate. Agreed at 2022-04-27 meeting to close issue.
