### ISSUE TITLE
What tools are needed to make CoverageJSON more successful?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#123]
1. A python validation tool to validate values and aspects that the JSON Schema cannot.
2. ??

**Comment by jonblower** [comment]
To add to this, my idea for the Python tool is that it would convert CovJSON objects into common frameworks like xarray, geopandas etc, ready for analysis and plotting. Along the way it would do validation of "the parts the schema can't reach".

And it would also write CovJSON from those common frameworks although that's a little trickier as not all the information may be present.

**Comment by chris-little** [comment]
@jonblower Maybe Zarr should be on the framework list? And the validation component could be reuseable elsewhere?

**Comment by jonblower** [comment]
Yes, agreed on both points

**Comment by edzer** [comment]
A GDAL CovJSON read & create driver, supporting the [GDAL multidimensional array API](https://gdal.org/api/index.html#multi-dimensional-array-api). That would allow conversion into other MDA types (NetCDF, Zarr) using `gdalmdimtranslate`, and easier uptake in OSGEO software building on GDAL.

**Comment by jonblower** [comment]
Great idea @edzer! Would such a driver have to be written in C, or could it be done in Python?

**Comment by edzer** [comment]
I think easiest is in C++ - the NetCDF, Zarr and MEM driver implementations could work as examples.

**Comment by chris-little** [comment]
It may be worth investigating whether COverageJSON (and API EDR) could be a useful adjunct to [ERDDAP](https://coastwatch.pfeg.noaa.gov/erddap/index.html)

**Comment by chris-little** [comment]
How about some closer interaction between COverageJSON and the STAC ecosystem? STAC is rather space imagery orientated, but perhaps CoverageJSON could fill some gaps around GeoTIFF and COG?

**Comment by jonblower** [comment]
I think CoverageJSON could be a useful format for an "asset" in a STAC catalogue. STAC can point to pretty much any format (using the media type, which is one reason why #135 is important). So GeoTIFFs and CoGs can already be arranged in a STAC catalogue.

I may be wrong, but I don't think anything further needs to be done to integrate CoverageJSON with STAC as they are neatly complementary. But it would be cool to build in some CoverageJSON visualisation into the [STAC browser](https://github.com/radiantearth/stac-browser) so they can be automatically previewed, in the same way that GeoTIFF can be.

**Comment by chris-little** [comment]
@jonblower @edzer The above issues have now been separated into single topic issues, so closing this generic issue.
