### ISSUE TITLE
What criteria to move CoverageJSON from Community to Full OGC Standard?

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#125]
The reasons for making CoverageJSON an OGC Community standard included lack of governance infrastructure, lack of developmental roadmap, higher visibility, improved synergy with other OGC standards, especially the new OGC APIs, an improved specification and enabling quotation in procurements. 
What are the Pros and Cons of remaining an OGC Community Standard or becoming a full OGC Standard?

**Comment by chris-little** [comment]
A number of other OGC Community Standards have developed, or are moving, to further versions of a community standard, such as:

- [3DTiles](http://docs.opengeospatial.org/cs/18-053r2/18-053r2.html) moving to V1.1
- [CityJSON1.0](https://docs.ogc.org/cs/20-072r2/20-072r2.html) moving to 1.1, 
- [I3S](https://docs.ogc.org/cs/20-072r2/20-072r2.html) moving to V1.3
- [LAS](https://portal.ogc.org/files/17-030r1) moved to V1.4

Maybe the sole criterion is a breaking change? I.e. V2.0.

**Comment by chris-little** [comment]
Some useful information from OGC staff:
No OGC Community Standard has yet transitioned to a full OGC Standard (Let's Not be first! ?)
Three tasks need to be accomplished, from the OGC point of view:
1.  Use the OGC Standard ASCIIDoc/Metanorma template. We are 80% done on this - we would need to clarify and number Requirements, Recommendations and Permissions, switch from IETF to ISO terminology (MUST/SHALL etc) and agree conformance classes for how the Requirements should be grouped 
2. Define an Abstract Test Suite (ATS) in an Annex A, indicating how the above Conformance Classes and their assertions would be tested. Again we are largely done - most tests would be validation against the CoverageJSON Schema. Some tests could be just by inspection.
3. IPR has to be handed over to OGC.

@jonblower @letmaik I suggest that as transition to a full standard is probably on a far horizon, and there do not seem to any Pro reasons, and a few Con, that we close this issue, and concentrate on our V1.1 and V1.2 roadmap.

**Comment by jonblower** [comment]
From what you say, I agree that we shouldn't focus on this for a while. Just wondering whether we should actually close the issue (which might mean we lose sight of the information here) or whether we should tag it "long-term" or something like that.

**Comment by jonblower** [comment]
As @KoalaGeo suggested in #131, we could consider running the schema validator as part of the OGC TeamEngine system. I assume we would only do this if CovJSON became a full OGC standard (hence noting it on this ticket), but @ghobona could correct me if I'm wrong.
