### ISSUE TITLE
Formatting issue in daily build?

### ISSUE THREAD

**Issue by jonblower** [opengeospatial/CoverageJSON#126]
In the "Examples" section of the daily build (section 10.6.1.3), is there an issue with the hyperlink syntax? The text appears as follows:

`Example of a domain object with ["Grid"][domain-types] domain type:`

I assume the "Grid" text is meant to hyperlink to the domain types section?

**Comment by edzer** [comment]
The also cookbook contains several references to https://covjson.org/domain-types/ , but that does not exist - I guess this is the same issue.

**Comment by jonblower** [comment]
Ooh, it looks like that link has got broken, thanks for pointing that out. @letmaik I guess we'll have to edit the cookbook text?

**Comment by letmaik** [comment]
See https://github.com/covjson/cookbook/issues/3 for the cookbook issue. Let's keep this one for spec formatting problems.

**Comment by chris-little** [comment]
@ghobona This is another formatting issue with the CoverageJSON spec that we do not understand and need guidance please.

**Comment by chris-little** [comment]
@jonblower @letmaik Anchors and link formatting now fixed by PR #137 and #142. Please note the spec text has a section `common_domain_types`, not `domain-types`.
