### ISSUE TITLE
Show TOC level 3 in rendered specification

### ISSUE THREAD

**Issue by letmaik** [opengeospatial/CoverageJSON#128]
The rendered spec at https://opengeospatial.github.io/ogcna-auto-review/21-069.html#toc23 only shows the first two levels of the TOC in the left side navigation. This is quite problematic as a lot of interesting content is in the third level, e.g. CoverageJSON objects (which has Domains below it). It makes consuming the spec harder than necessary and we didn't have that issue in the original non-OGC spec.

@ghobona Is there a way to show TOC level 3 as well?

**Comment by chris-little** [comment]
@ghobona Does this require a Metanorma infrastructure change? We have just reviewed the spec structure and it does not make sense to raise lower paragraphs to a higher level. Otherwise we would get the same problem as those standards that have a list of 99 Requirements

**Comment by chris-little** [comment]
@letmaik This is now a known bug in the Metanorma Content Management System:
"In contrast with documentation:
`toclevels` controls the PDF TOC levels only, and does not affect HTML or DOC outputs.
`htmltoclevels` controls the HTML TOC levels.
`doctoclevels` controls the DOC TOC levels."

So this is a bug that will be addressed here:
[https://github.com/metanorma/metanorma-ogc/issues/449](https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmetanorma%2Fmetanorma-ogc%2Fissues%2F449&data=05%7C01%7Cchris.little%40metoffice.gov.uk%7Cb5fbf78357874730dedb08dabbd50149%7C17f1816120d7474687fd50fe3e3b6619%7C0%7C0%7C638028820773972782%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=vquhZfN41TlNQhKH%2FEShO89aH0mcrF5vc0ATKDMyX3Q%3D&reserved=0)
