### ISSUE TITLE
Use of colon in media types

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/CoverageJSON#130]
After reading https://github.com/opengeospatial/ogcapi-features/issues/759 

Is there an issue with https://opengeospatial.github.io/ogcna-auto-review/21-069.html#toc28 

> The CoverageJSON media type SHALL be application/prs.coverage+json with an optional parameter profile which is a non-empty list of space-separated URIs identifying specific constraints or conventions that apply to a CoverageJSON document according to [RFC6906](http://www.ietf.org/rfc/rfc6906.txt).

**Comment by chris-little** [comment]
@nmtoken Thank you for noticing that. We can discuss it in 3 hours time at a Task Team GoToMeeting.

As CoverageJSON is not an OGC GML-derived standard, it may be wider than OGC involving IANA and W3C.

**Comment by letmaik** [comment]
Not an issue it looks like, see https://github.com/opengeospatial/NamingAuthority/issues/194#issuecomment-1239234258.

**Comment by chris-little** [comment]
Perhaps we could add a sentence to remind that the non-empty list will need to be a quoted string as special characters are involved.

**Comment by chris-little** [comment]
As @jonblower siad, probably nobody is using this profile option yet, so we can fix with the statement above, if we agree.

**Comment by letmaik** [comment]
Yes, you can add a note saying that if this media type is used in the content-type HTTP header, then the value of the profile parameter must be quoted as profile URIs include special characters (colon). See also https://www.rfc-editor.org/rfc/rfc2616#section-3.6.

**Comment by chris-little** [comment]
@jonblower will add above text from @letmaik to the PR for adding HTML anchors to the spec.

**Comment by chris-little** [comment]
@jonblower @nmtoken PR#140 addresses this.

**Comment by chris-little** [comment]
Fixed by PR#140
