### ISSUE TITLE
Media type for CoverageJSON

### ISSUE THREAD

**Issue by jonblower** [opengeospatial/CoverageJSON#135]
I think this has been discussed elsewhere but I can't find the link at the moment.

At the moment we use the media type `application/prs.coverage+json`. I'm not sure the `prs` prefix (which means "personal" or "vanity" project) is appropriate. The [STAC best practices](https://github.com/radiantearth/stac-spec/blob/master/best-practices.md#formats-with-no-registered-media-type) suggests that a `vnd` prefix (for "publicly-accessible but vendor produced") is appropriate. Note that a "vendor" can be a consortium or non-profit entity, according to [Wikipedia](https://en.wikipedia.org/wiki/Media_type#Vendor_tree).

Maybe this is a wider OGC issue, although as a Community Standard I don't know where CoverageJSON would stand.

If we did change this, I'm not sure what the implication would be for implementations. Maybe there are not many implementations that depend on the MIME type?

Thoughts @chris-little, @letmaik, @ghobona ?

**Comment by jonblower** [comment]
Just to note that the EDR API makes a reference to the current CoverageJSON media type - see https://docs.ogc.org/is/19-086r5/19-086r5.html#toc15. Need to bear this in mind if we consider a change.

**Comment by jonblower** [comment]
Some precedents:
- GeoJSON media type is `application/geo+json`
- JSON-LD media type is `application/ld+json`
- [JSON-FG](https://docs.ogc.org/DRAFTS/21-045.html#application_fg_json) is using `application/vnd.ogc.fg+json` as a preliminary media type "until this Standard is stable to avoid confusing future implementations accessing JSON documents from draft versions of this Standard."

**Comment by chris-little** [comment]
@jonblower I have emailed @ogcscotts for any OGC Policy for a preferred media type.

**Comment by ogcscotts** [comment]
@chris-little @jonblower OGC would prefer not to use the "vnd" prefix because the specification is published and used and if a Community Standard, then we'd like it to be treated like our other Standards (GeoPackage, GML, etc.).

**Comment by chris-little** [comment]
@ogcscotts So does that suggest that the media type should be something like `application/covjson+json` ?

- GeoPackage: `application/geopackage+sqlite3`
- GML: `application/gml+xml'

**Comment by ogcscotts** [comment]
@chris-little I think that pattern would be best

**Comment by letmaik** [comment]
@ogcscotts I don't think `application/covjson+json` makes sense. If anything, then `application/coverage+json`, but getting there will take a bit longer.

**Comment by ogcscotts** [comment]
@letmaik there are examples of both styles in IANA. Another OGC Community Standard (CityJSON) follows the pattern you suggest (city+json). I expect that coverage+json could become a little contentious if CIS-JSON is to move forward.

**Comment by letmaik** [comment]
@ogcscotts Good point. Well, there's always `application/cov+json` or  `application/cis+json`, depending on who gets `coverage`. I think it's too early for that though.
Is OGC objecting `vnd` completely, or just `vnd.ogc`? Maybe `application/vnd.coverage+json` or `application/vnd.cov+json` is possible. The latter may be more future-proof to avoid conflict with CIS, and could eventually become `application/cov+json`.

**Comment by ogcscotts** [comment]
@letmaik the vnd pattern would be fine. I think the idea of using vnd now and looking toward a change in registration later is good.

**Comment by chris-little** [comment]
@letmaik @ogcscotts The CoverageJSON Task Team discussed this on 2022-11-02 and unless other views expressed, `application/vnd.cov+json` proposed for publication as a comunity standard rather than the existing `application/prs.coverage+json`. Then later, with implementaton evidence, move to `application/cov+json

**Comment by chris-little** [comment]
@jonblower @letmaik @ogcscotts This consensus implemented by PR#141
