### ISSUE TITLE
Discoverability of internals of OGC specs.

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#145]
It is not clear whether all the sections, sub-sections and other components of an OGC spec are discoverable from the web. For example, the PDF and HTML versions seem to use automatically generated anchors frm the Metanorma content managment system.

**Comment by chris-little** [comment]
@ghobona explained that Table of Contents links into the PDF and HTML version of the standard would be automatically generated, and so are not easily predicted, and may change.
But manually inserted anchors maintain a predictable URL.
As I have now inserted such anchors for all the main sections ofthe Standard, I propose to close this issue. 
@jonblower and @letmaik Do you agree?

**Comment by letmaik** [comment]
Fine with me.

**Comment by jonblower** [comment]
Although you've manually inserted anchors with meaningful names, these don't seem to appear as href anchors in the resulting HTML code. Maybe they can be used internally within the document to link sections together, but we still can't use them as permanent URL links to a given section.

For example, here's the HTML code for the "ParameterGroup Objects" section. Note that the manually-inserted anchor (`[[parametergroup_objects]]`) only appears as the id of the div, not as an href:

![image](https://user-images.githubusercontent.com/6309993/214788997-7b21d927-1e5b-4813-8947-d2c7b0da560e.png)

So it seems there is no solution for creating predictable, externally-referenceable links to a given section in the document?

**Comment by chris-little** [comment]
@jonblower @ghobona @letmaik I've just asked Ron Tse (owner of Ribose and MetaNorma) for help. (Couldn't find his GitHub handle)

**Comment by chris-little** [comment]
Many thanks to the Ribose Metanomra staff for a solution - The AsciiDoc anchors in the source are wrong: `[[This Section]]` is not valid AsciiDoc, there should be no white space, so `[[ThisSection]]` should give a predictable external URL.
I will prepare a PR to correct Version 1.0 before publication.

**Comment by chris-little** [comment]
@jonblower @letmaik The links that I inserted into the AsciiDoc source all work in the HTML version e.g. https://opengeospatial.github.io/ogcna-auto-review/21-069.html#polygonseries
