### ISSUE TITLE
Update JSON-LD text, context doc and prefix registry?

### ISSUE THREAD

**Issue by jonblower** [opengeospatial/CoverageJSON#147]
It is probably worth reviewing the text around the use of JSON-LD (see [spec daily build](https://opengeospatial.github.io/ogcna-auto-review/21-069.html#toc36)), and consider whether we need to move the [context doc](https://covjson.org/context.jsonld) and [prefix registry](https://covjson.org/prefixes/) to new homes in the OGC space?

Note that this relates to the issue about extracting building blocks from the CoverageJSON spec (see #139), as it would greatly help to have stable URIs.

What do you think, @letmaik?

**Comment by chris-little** [comment]
@jonblower @letmaik The [OGC Schema Repository](https://schemas.opengis.net/) is not a GitHub repo, but just a hierarchical file system. Could we put everything into a single folder, called for example: `CovJSON`?

**Comment by letmaik** [comment]
I would roughly follow https://schemas.opengis.net/cis/, so there would be at minimum: 

https://schemas.opengis.net/covjson/
https://schemas.opengis.net/covjson/ReadMe.txt
https://schemas.opengis.net/covjson/1.0/
https://schemas.opengis.net/covjson/1.0/coveragejson.json  (JSON Schema)

I'm not sure about the JSON-LD context doc and the prefix registry. They are a mix of schema and vocabulary. Maybe new vocabulary would go in https://defs.opengis.net/vocprez/vocab/ but then the JSON-LD context doc still has to live somewhere. Maybe it's ok for 1.0 to keep them at covjson.org and only host the JSON Schema on opengis.net.

**Comment by chris-little** [comment]
@ghobona @ogcscotts I think the structure of the CoverageJSON schema files from @letmaik is fine. The question is where should the JSON-LD context files and prefix registry go?
Am I correct in thinking that the vocprez branch is probably outdated legacy?

**Comment by chris-little** [comment]
Agreed on 25 Jan 2023 to put all the files (schemas, context files, prefixes) on the OGC Shema files system schemas.opengis.net.

**Comment by chris-little** [comment]
When schemas etc copied into OGC schema repo, and the Community Standard is published, the community needs to agree on a closing date for the community site. It could be a few years away.

**Comment by ghobona** [comment]
@chris-little and @ghobona discussed the topic during the 2023-02-08 CoverageJSON telecon and agreed that the context document should be placed at https://covjson.org/context.jsonld

There was also agreement to leave the prefix page at https://covjson.org/prefixes/

@jonblower @letmaik Do you have any objection to this resolution?
