### ISSUE TITLE
Vertical CRS example

### ISSUE THREAD

**Issue by RogerLott** [opengeospatial/CoverageJSON#151]
Minor typographic issue. In 5.1.3.  Vertical Coordinate Reference Systems example the correct acronym is NAVD88 (not NAV88). But more of an issue is that NAVD88 is used primarily in the US and often in feet. EPSG:5703 is the metric version, different ids represent the system in feet and US Survey feet (EPSG:8228 and EPSG:6360 respectively). Proposed minor editorial correction: change 
"Example of a vertical CRS, here representing height above the NAV88 datum:" 
to 
"Example of a vertical CRS, here representing height above the NAVD88 datum in metres:".  
[Alternative would be to use the US rendition "... in meters:" or "... in metres (meters):"]

**Comment by jonblower** [comment]
Many thanks @RogerLott - I've raised a PR: https://github.com/opengeospatial/CoverageJSON/pull/152
