### ISSUE TITLE
MERMAID UML diagram does not render in MetaNorma

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#156]
@ghobona We inserted a simple top level [UML diagram](https://github.com/opengeospatial/CoverageJSON/blob/master/standard/clause_specification_text.adoc) using Mermaid. This has not rendered at all in the [nightly build](https://opengeospatial.github.io/ogcna-auto-review/21-069.html). How can we get the diagram into the final standard please?

**Comment by jonblower** [comment]
I think we need to reopen this as the [daily build](https://opengeospatial.github.io/ogcna-auto-review/21-069.html#toc19) does not render the UML. Maybe there is a syntax error - @ghobona can you spot anything?

**Comment by jonblower** [comment]
Fixed by PR #160 - thanks to @ghobona
