### ISSUE TITLE
How to plan the work, short and longer term

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#19]
We will have things to do:
1. Get CoverageJSON adopted as a community standard;
2. Detailed comparison with other Coverage payloads such as CISJSON and GeoTIFF;
3. Agree enhancements for the next version of CoverageJSON, preferably V1.1 so backwards compatible;
4. Agree which enhancements are breaking changes for V2.0.

How should we structure the GitHub repo for these?

**Comment by jonblower** [comment]
I think that using tags in the Issues to distinguish the target for each issue (e.g. necessary to enable adoption, future enhancement, comparison) would be useful.

**Comment by chris-little** [comment]
@jonblower so the new top level plan could be ?
    
1. Agree and fix certain issues from original GitHub repo first
2. Get CoverageJSON adopted as a community standard (aim for March 2022);
3.  Detailed comparison with other Coverage payloads such as CISJSON and GeoTIFF; 
4.  Agree enhancements for the next version of CoverageJSON, preferably V1.1 so backwards compatible;
5. Agree which enhancements are breaking changes for V2.0.

**Comment by chris-little** [comment]
As the project structure has been established, this can be closed
