### ISSUE TITLE
Clarify high level goals in preamble

### ISSUE THREAD

**Issue by jonblower** [opengeospatial/CoverageJSON#22]
It would be helpful to be clear about the goals of CovJSON and the targets it's aiming at, e.g.:

 * designed for web APIs (it's not an archive format for data in bulk)
 * able to encode gridded and non-gridded data (include some real world examples)
 * some notes about handling large data sets (since this is often the first concern when thinking about JSON)
 * ...

This info is currently scattered around the CovJSON website and spec but could be consolidated.

**Comment by chris-little** [comment]
@jonblower (I should be having supper) I think these goals could be added to the spec in this repo. I suggest in  perhaps the [Abstract](https://github.com/opengeospatial/CoverageJSON/blob/master/standard_template/standard/clause_0_front_material.adoc) and in the [scope](https://github.com/opengeospatial/CoverageJSON/blob/master/standard_template/standard/clause_1_scope.adoc) and in the top level readme?
