### ISSUE TITLE
Clause 1- Scope should clarify the scope (i.e technical scope) of this OGC standard

### ISSUE THREAD

**Issue by EmDevys** [opengeospatial/CoverageJSON#24]
Though contextual information (currently provided in this clause) is of interest, the Scope should define the technical scope of this OGC standard.
In addition to this, please take account of the fact that the current status of CovJSON is only an open specification, used by some communities and provided under covJSON.org, that does NOT yet have the status of a de jure standard, as it is not presently adopted by any standardisation body (to my knowledge).
therefore, when reference to CovJSON as of covJSON.org, please avoid the term standard, and rather use specification, or any term at your convenience.

**Comment by chris-little** [comment]
I will prepare a PR to remove references to `standard`

**Comment by chris-little** [comment]
The document now only refers to a `specification` rathern than `standard`.

**Comment by chris-little** [comment]
Two PRs created to address spec/standard terminology and clarified technical scope.

**Comment by chris-little** [comment]
Addressed by PR #30 and #48
