### ISSUE TITLE
Vote Comment - 1.6 Alignment with OGC Standards Baseline

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#33]
Part of First comment submitted in the Technical Committee vote to commence Work:
Sentences “As CoverageJSON is a format for data, it cannot conform to the required operations of ISO19123:2005, though the CoverageJSON components seem sufficient to support any simple continuous or discrete coverages.
So in this sense, CoverageJSON is consistent with the OGC Abstract Specification Topic 6 / ISO 19123 Coverage Model [10].”
Does this really make sense? It is doubtful that CovJSON is consistent / conformant with AS Topic 6 / ISO 19123 data model, when the definition of Coverage, Domain and Range in ISO 19123 do not apply to this submitted document. It should be noted that the section 1.3 Definitions in CovJSON specification do not provide (or reference) the ISO 19123, and that the Coverage JSON schema specified is not directly mappable with the Coverage data model (in ISO 19123 / AS Topic 6) of in CIS associated UML implementation model. The gap goes beyond the operations addressed by the optional CoverageFunction property in the Coverage data model. The text about this “consistency” with AS Topic 6 should be clarified (or suppressed).

**Comment by chris-little** [comment]
The specification has been updated in this repo and references OGC Abstract Topic 6 / ISO19123:2005.

CoverageJSON was intended and designed to conform to the OGC Abstract Topic 6 / ISO19123:2005 concept of a coverage, in as much as a data format can support the specified 5 operations, 3 associations and 3 attributes. Work to compare and constrast the CoverageJSON functionality with that of CIS JSON, GeoTIFF, NetCDF and the ISO19123 standard has been planned in the Coverage SWG and is just starting, using this repo.

`the Coverage JSON schema specified is not directly mappable with the Coverage data model ... of in CIS associated UML implementation model` This statement needs more detail as what was implied, as at the time of writing, there was no CoverageJSON schema, only definitions of the JSON objects.I believe that JSON Schema did not exist at the time of the development of CoverageJSON. A formal JSON schema is now being developed to allow conformance testing. This may help the comparison work already mentioned.

**Comment by jonblower** [comment]
> I believe that JSON Schema did not exist at the time of the development of CoverageJSON

I'm not sure - I think it did exist but was certainly less mature and lacked some of the features we are now using. It's much easier now to deal with complex schemas

**Comment by chris-little** [comment]
Once realtionship to existing OGC coverage standards are clarified in the Spec, we will close the issue

**Comment by chris-little** [comment]
The specification now states `The specification is a logical implementation of the long-established abstract conceptual standard ISO19123:2005 (also known as OGC Abstract Topic 6)` so I propose to close the issue at the meeting of 2022-04-27 as addressed.

**Comment by chris-little** [comment]
Agreed to improve the text of the Scope clause

**Comment by chris-little** [comment]
@jonblower Hopefully addressed by PR #70

**Comment by chris-little** [comment]
Agreed to close at 2022-05-04 meeting
