### ISSUE TITLE
Vote Comment - 1.9 ranges and rangeAlternates

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#35]
Part of First comment submitted in the Technical Committee vote to commence Work:
The rule that “ranges” (supposed to be mandated) may be empty and "rangeAlternates" used instead, and “clients are expected to have support for the alternative range format(s)” is unclear and presumably does not facilitate clients. In addition, such rangeAlternates and rule does not facilitate interoperability with OGC CIS Coverage schema.

**Comment by jonblower** [comment]
I would be willing to omit the section that mentions "rangeAlternates" and leave this for a future version of the spec. It's not well defined (it's there as a placeholder/hook to enable linkages to other data formats).

**Comment by chris-little** [comment]
@jonblower I agree - let us remove the mention of `rangeAlternate`. Presumably we (you?) need to change text and perhaps alter the cardinality of range?

**Comment by jonblower** [comment]
Yes, agreed - the only reason to allow an empty range would be if we allowed rangeAlternates.

**Comment by chris-little** [comment]
PR meerged at 2022-04-06 meeting, so issue closed
