### ISSUE TITLE
PC02:- CoverageJSON does not support coverages

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#5]
Comment 25 June 2021:
CoverageJSON does not support coverages, this has been stated by several experts independently in detail.

**Comment by chris-little** [comment]
1. We would like sight of the evidence. Other experts (Scott Simmons, Jon Blower, Joan Maso, etc) think it does support coverages, and have stated so in OGC forums.
2. CoverageJSON is a data format, not a function as defined by ISO19123 [?], but it does support the items needs for a coverage function sucsh as an explicit domain set, and implicit range set.
3. It is not clear that COverageJSON is better or worse than other data formats supporting coverages, such as GeoTiff and NetCDF.
4. We knkow that CoverageJSON can support both discrete and continuous coverages, in the sense of ISO19123.
5. CoverageJSON was explicitly invented to support a general definition of a coverage (i.e. a function mapping from a domain to a range) .
6. The Supporters agree, NOTUC, to obtain the detailed expert statements for further consideration.

**Comment by chris-little** [comment]
An email comment between two geospatial experts, @ogcscotts and Peter Parslow, dated 2021-08-11: `Both CoverageJSON and CIS JSON are valid implementations of the Abstract spec, but there are some differences`

**Comment by pebau** [comment]
An easy way to demonstrate equivalence of both JSON encodings would be to do a roundtrip: formulate relevant coverages, transform them into the other representation, then back again, and see whether the result contains all information provided initially. The above comment suggests there will be difficulties, but the proof is in the pudding.

**Comment by chris-little** [comment]
@pebau A round trip exercise is a very useful suggestion, though there may be a significant amount of work. I suggest that it is part of the Coverages SWG work on an OGC Discussion Paper comparing the coverage formats in detail (though is does sound more like an Engineering Report).

Besides GeoServer, are there any [Coverage implementations listed](https://github.com/opengeospatial/CoverageJSON/tree/master/implementations#readme) that could produce or ingest CIS JSON, to minimise code development? I assume Geoserver can ingest CIS JSON. I will raise another issue covering this topic, ad ther is a lot of detail (e.g. continuous versus discrete coverages).

Meanwhile, this does not concern your original comment, so I propose closing this specific Issue #5 next week, once people have had time to consider.

**Comment by chris-little** [comment]
CLosed as no further correpsondance recieved.
