### ISSUE TITLE
propose removal of bespoke in line crs

### ISSUE THREAD

**Issue by marqh** [opengeospatial/CoverageJSON#59]
https://github.com/opengeospatial/CoverageJSON/blob/master/standard_template/standard/clause_specification_text.adoc#514-providing-inline-definitions-of-crss

the bespoke in line definition is likely to alter significantly as https://github.com/opengeospatial/CoverageJSON/issues/26 and similar angles are pursued

given the liklihood of these options for 1.1, having this bespoke syntax in 1.0 seems to be storing up problems for backwards compatability

i propose removng this section from the 1.0 version

(this is a long standing discussion: https://github.com/covjson/specification/pull/89)

the external link to a published CRS seems sufficient for v1.0

**Comment by jonblower** [comment]
I'm also in favour of removing (or at least deprecating) this for 1.0. I'm not aware of anyone that's using the bespoke syntax anyway and it's not well defined.

**Comment by marqh** [comment]
hi @jonblower 

i think that i would prefer option 3 and to remove this altogether, and have it out of scope for 1.0

i think that having non-normative setctions with unstandardised contents is risky and encourages use that we will change in the future

**Comment by marqh** [comment]
i agree that providing a description field for the CRS is useful

people can always add contextual descriptions for humans

in the scenario where no CRS URI can be used, a text description only is better than nothing

**Comment by jonblower** [comment]
> in the scenario where no CRS URI can be used, a text description only is better than nothing

So does that mean you'd support option 2?

I see this as analogous to what GeoJSON does: GeoJSON only supports CRS84, but has some text that says "use other CRSs if you want, but that's outside the spec and would be application-specific".

**Comment by jonblower** [comment]
Their [wording](https://datatracker.ietf.org/doc/html/rfc7946#section-4) is, "where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted."

**Comment by marqh** [comment]
i think that we should ensure that the 'id' remains used for the identifier of the CRS
the current text is clear on this

i think adding a description attribute is useful

i'm wary of adding an attribute name to store anything else, or giving options for the `id` to be used to encode non-standard encodings

description is already free text in other uses, and can be co-opted for non-standardised exchange

So, i prefer removing the section on in-line definitions all together and adding the optional description field to the other sections defining use
