### ISSUE TITLE
PC03: Support coverages as per standard, or rename

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#6]
Comment, 25 June 2021:
1. Requirement: General
2. Implementation Specification Section number: all
3. Criticality: critical
4. Comments/justifications for changes: 
either make it support coverages as per standard, or rename it to not continue any reference coverages

**Comment by chris-little** [comment]
1. CoverageJSON is a de facto community, open source, format that is being proposed as an OGC COmmunity Standard. Renaming would serve no benefit to the user communities, and OGC Members, and the Supporters do not have this power.
2. there are no benefits in changing at this stage the successful, widely used, community implementations. we are proposing that any changes be consdiered for future work, within the OGC. This give the community the benefit of a focal point for future developments.
The supporters reject this comment on the grounds that outside of OGC, there is no power to change the specification or rename it. This may change in the future. NOTUC
2. Repeat some of the arguments from previous issue #5

**Comment by pebau** [comment]
Hm...can the supporters rightfully reject? If the name "coverage" is used I cannot see how the Coverages SWG can get bypassed.

**Comment by chris-little** [comment]
@pebau Of course the  `supporters [can] rightfully reject` - they are responsible for their software investments and to their users. There is no intention that `Coverages SWG can get bypassed'. The Community Standard process does not need a SWG or DWG - it needs the supporters to propose a document to OGC. Once the CoverageJSON document is an OGC document, some Coverage SWG members have agreed to work on a detailed comparison (Discussion Paper) and this should produce some well-founded recomendations for the way forward. That is up to the Coverages SWG. Meanwhile, CoverageJSON users are doing their own thing outwith OGC.

The group had agreed that your original issue above was addressed and could be closed.
