### ISSUE TITLE
Figure out how to embed final 1.0 spec in the covjson.org website

### ISSUE THREAD

**Issue by jonblower** [opengeospatial/CoverageJSON#66]
We will retire the previous GitHub repo containing the original specification, and continue future discussions here. But we will need to embed the eventual OGC-approved spec in the covjson.org website. We should figure out if we can do this automatically. Also we may in future need to provide access to two versions: the latest release and the current in-progress draft.

**Comment by chris-little** [comment]
@ghobona When the specification is adopted as an OGC Community Standard, can we automatically copy to the original spec web site, http://covjson.org, perhaps with a script? And then subsequently when corrigenda or V1.x are created?

**Comment by chris-little** [comment]
@jonblower @letmaik If fully automatic repopualtion of the CovJSON.org repo not possible, would a one-off manual cloning/copying be acceptable?

**Comment by letmaik** [comment]
I propose two things:
1. Set-up GitHub Actions on this repo to publish the latest commit to `main` to GitHub pages to https://opengeospatial.github.io/CoverageJSON/draft.html or similar. This will help spot outstanding issues during editing/development.
2. Once 1.0.0 is published somewhere as HTML on OGC's servers, embed that via an iframe in the covjson.org website. Anything more complicated (possibly replicated) would be too much effort and also creates uncertainty on whether a mirrored version is up-to-date or has been changed (possibly unintended).

**Comment by ghobona** [comment]
Yes, we can create cron job or GitHub Action to automatically copy to the original spec web site.

We would need the administrator of the original spec web site to liaise with the OGC Infrastructure Office (@gbuehler) regarding credentials.

**Comment by chris-little** [comment]
Agreed that @jonblower and @letmaik will set up two iframes on the covjson.org website for standard spec and current working draft once the standard approved.

**Comment by letmaik** [comment]
Done in https://github.com/covjson/covjson.github.io/pull/7. See https://covjson.org/spec/.
See the PR description on why it's not an iframe but a link only.
