### ISSUE TITLE
Switch to new OGC template

### ISSUE THREAD

**Issue by letmaik** [opengeospatial/CoverageJSON#74]
The OGC template has recently switched to using Metanorma (still Asciidoc based) for generating the outputs, see also https://github.com/opengeospatial/templates/tree/master/standard.

@ghobona Is it a requirement to switch in-development specs to the new template using Metanorma before publishing the first version? If not, then this can possibly be done for the next version. Any advice on advantages/disadvantages would be helpful.

**Comment by ghobona** [comment]
Since the document was already in asciidoctor-asciidoc, OGC and Ribose staff will convert the document to metanorma-asciidoc after the document has been approved by the TC.

**Comment by letmaik** [comment]
Thanks!
