### ISSUE TITLE
Set-up continuous integration to publish drafts to GitHub Pages

### ISSUE THREAD

**Issue by letmaik** [opengeospatial/CoverageJSON#75]
Suggested in https://github.com/opengeospatial/CoverageJSON/issues/66#issuecomment-1126924912:
> Set-up GitHub Actions on this repo to publish the latest commit to master to GitHub pages to https://opengeospatial.github.io/CoverageJSON/draft.html or similar. This will help spot outstanding issues during editing/development.

Dependencies: #73 and possibly #74.

**Comment by chris-little** [comment]
@ghobona Aae tou happy with this and alignment with OGC publishing procedures with Ribose? We wnat to be able to generate latest drafts automatically. We failed to get that to work over thel ast year with API EDR.

**Comment by ghobona** [comment]
@chris-little As of earlier this month, we now have a [prototype GitHub Action](https://github.com/opengeospatial/ogcna-auto-review/actions) that we can use to build OGC metanorma-asciidoc documents. The action is currently configured to build a document once a day but can be modified to use other triggers. There are some checks that metanorma does during the build process, however there are other checks that we would like to implement in the future. The prototype, when complete, will offer checks for conformance to OGC-NA policies.

**Comment by ghobona** [comment]
Cc: @ronaldtse @gbuehler

**Comment by letmaik** [comment]
@ghobona Keep in mind this project would benefit from CI *now*. This means either it is converted to the new Metanorma template first to be able to use the mentioned GitHub Actions, or a custom setup is done. Which do you suggest?

**Comment by ghobona** [comment]
The GitHub Action has been created at https://github.com/opengeospatial/CoverageJSON/blob/master/.github/workflows/generate_21-069.yml

The PDF and HTML documents are placed in the [root folder](https://github.com/opengeospatial/CoverageJSON) of the repository.

**Comment by letmaik** [comment]
Thanks @ghobona, I think this is a better solution. I think long term, once the reusable OGC/Metanorma GitHub Action reaches a stable state, it would be preferable to have the action in the CoverageJSON repository itself, to avoid the 1-day delay between commit and HTML update. Do you agree?

**Comment by chris-little** [comment]
@ghobona @jonblower @letmaik [Proposed standard](https://portal.ogc.org/files/?artifact_id=101016&version=) and [current working draft](https://opengeospatial.github.io/ogcna-auto-review/21-069.html) now set up, so agreed to close at 2022-05-25 Task Team meeting
