### ISSUE TITLE
Should Annex A be removed?

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/CoverageJSON#78]
Annex A appears to be unused.

![Screenshot 2022-05-20 at 14 19 48](https://user-images.githubusercontent.com/18121038/169541725-e98a2c43-91d2-4d53-a847-b09b03d279f0.png)

Should it be removed?

If Annex A is removed, then Clause 2 (Conformance) has to be updated accordingly.

**Comment by chris-little** [comment]
@ghobona We were not sure how to use Annex A. There is a JSON Schema bundle, now part of the spec, which has also been incorporated into the [CoverageJSON sandbox](https://covjson.org/playground/) which can test files for conformance.  We could also insert text pointing to the [schema](https://github.com/covjson/covjson-validator/tree/main/schemas) in its orginal place, and suggesting the sandbox/playground, as well as highlighting the [Cookbook](https://covjson.org/cookbook/).
I think Scott had said pointing to the community schema would be acceptable.
@jonblower @letmaik for info and suggestions

**Comment by chris-little** [comment]
@ghobona @jonblower We could remove Annex A and then add similar to the above text to Chapter 2. The only conformance class is that a CoverageJSON object is a valid JSON object and conforms to the CoverageJSON schema.
I think I prefer this approach. We can discuss in the Task Team meeting today Wednesday 25 May 2022 at 14:00 UTC (15:00 BST, 10:00 EDT)

**Comment by chris-little** [comment]
Fixed by merge of PR#83.
