### ISSUE TITLE
IPR status needs confirming

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/CoverageJSON#8]
The [original specification](https://covjson.org/spec/) states 
`Copyright © 2015 by ... . This work is licensed under a Creative Commons Attribution 4.0 International License.`
Any published OGC document will presumably be OGC Copyright, but it needs to be confirmed that the contents will be freely available.

**Comment by jonblower** [comment]
Following email conversations I think that the IPR status will probably be that the University of Reading would keep ownership but continue to licence openly. The README would need to include the statement:

"The contributor understands that any contributions, if accepted by the OGC Membership, shall be incorporated into OGC standards documents and that all copyright and intellectual property shall be vested to the University of Reading."

Anyone will be able to contribute under these terms, not just OGC members.

@ogcscotts confirms that the above can still be asserted even after OGC endorsement of the Community Standard.

**Comment by chris-little** [comment]
@ogcscotts Cold you confirm that you are happy for the above text from @jonblower to be added to this repo top-level README file ?
And what changes should be made to the OGC front matter to reflect Reading University's IPR please?

**Comment by ogcscotts** [comment]
@chris-little As a Community Standard, this text is fine as the University of Reading will retain the intellectual property and OGC merely republishes the work with the University's permission.

**Comment by chris-little** [comment]
The text has ben incorporated into this GitHub repo top level README file. I propose to close the issue at the 2022-04-27 meeting.
