### ISSUE TITLE
Set-up branch protection on `main`

### ISSUE THREAD

**Issue by letmaik** [opengeospatial/CoverageJSON#80]
To prevent PRs getting merged without approving reviews.

**Comment by chris-little** [comment]
@ghobona @gbuehler I do not seem to be able to set up compulsory reviewing for Pull Requests. Probably ignorance on my part, or maybe not enough status.
I suggest at least two out of three @jonblower @chris-little @letmaik .

**Comment by chris-little** [comment]
I now have some admin rights and can assign reviews etc. @letmaik @jonblower I propose to close this this afternoon at the tas team meeting

**Comment by chris-little** [comment]
Agreed at 2022-06-29 meeting to close
