### ISSUE TITLE
Fix broken links

### ISSUE THREAD

**Issue by letmaik** [opengeospatial/CoverageJSON#88]
- 6.6.4.  Coverage Objects: broken link to example at the end (should reference section B.1 instead)
- 6.6.5.  Coverage Collection Objects: broken link to domain types section & broken link to coverage collection example (should be B.2)

**Comment by chris-little** [comment]
@ghobona Fixed in PR #91, but not clear whether new links are the correct format

**Comment by chris-little** [comment]
@ghobona PR #91 merged, but not clear whether links should contain the `.../blob/master/...` string or not.

**Comment by chris-little** [comment]
We can close this when the daily build is working and we can confirm the links are inthe correct format.

**Comment by chris-little** [comment]
@letmaik Issue was with ASCII Doc links, not URLs. Fixed by PR #95
