### ISSUE TITLE
Checking Hyrax (bes) covjson responses against covjson test suite

### ISSUE THREAD

**Issue by lewismc** [opengeospatial/CoverageJSON#96]
I have been [documenting various issues with the covjson responses](https://github.com/OPENDAP/bes/issues/650) generated by OPeNDAP Hyrax (1.16.0).
Before I go down the rabbit hole, it would be great if I could literally test a given covjson file against a test suite. I vividly remember seeing mention of a test suite somewhere...?
Is this possible?
Thanks for any info...

**Comment by chris-little** [comment]
@lewismc Can we close this issue? There is a PR imminent with increased prominence for the schema.

**Comment by chris-little** [comment]
@lewismc PR highlighting schema and community sandbox now reviewed and merged.
